### ISSUE TITLE
monitor.py regression

### ISSUE THREAD

**Issue by sethroot** [wgoulet/CTPyClient#4]
the code that was added to prevent a name error crash in this commit: f42cdd001f5221802d27217fed909084084dd3ee

has been removed in this commit: 8e5cc1da5a659231efa088694f77f94ffdf7ab35

so now monitor.py is crashing again when crypto.load_certificate() returns None

**Comment by wgoulet** [comment]
Thanks; fixed.

**Comment by sethroot** [comment]
You still need to add in an initialization of the subject var or else you will get "UnboundLocalError: local variable 'subject' referenced before assignment" in the except block

see: https://github.com/wgoulet/CTPyClient/blob/f42cdd001f5221802d27217fed909084084dd3ee/monitor.py#L108

**Comment by wgoulet** [comment]
Got it; I actually refactored that function to not print the subject (and use the var) if an exception is thrown when I try to decode the certificate data.
